print("hello world")
print("hello" + " " + "world")
print(1 + 1 + 1)
print("1" + "1" + "1")
print("1" + "1" + "1" + "1")
print("You can do this Minh Anh!")
print("Check another one!")
print("idk what to write")
print("I am so tired")
print("I want to sleep")
